server:
  port: 10086
spring:
  application:
    name: gateway-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
ribbon:
  ConnectTimeout: 250
  ReadTimeout: 2000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 10000
zuul:
  retryable: true
  routes:
    item-server: /item/**
  prefix: /api